### PR TITLE
[M2] Added search engine key word functionality and ability to return a list

### LINKED ISSUE #34: [M2] Allow search engine to return a list of most relevant results rather than just one

### LINKED ISSUE #35: [M2] implement key words when adding to search engine data
# Overview
Since web scraping the links in the search engine won't always work, it is important to allow users to add keywords to associate with the links. This way the search engine can still search for the link by comparing the search query with the keywords.
# Results
Added another parameter to the add_link(link, keywords="") method. Keywords can now be added along with the link. Since the keywords go through the same pre-processing as the query, you can input the keywords in whatever format. There is also a KEYWORD_WEIGHT constant that determines how much the search engine cares about the keywords. Eg: "KEYWORD_WEIGHT = 2" means that keywords are weighted twice as much as the web scraping during a search.

### LINKED ISSUE #36: [M2] Create tests for the search engine
# Overview
To make sure the search engine still works throughout the development process, additional tests must be added to the CI to ensure that after each commit, the search engine is still working.
# Results
New tests have been added to the CI that runs through GitHub actions.  These tests check for web scraping and keyword functionality as well as random inputs that check the engines error handling ability.

### PR DESCRIPTION
**Pull request by ashwin-godura**
(Resolves #34, resolves #35, resolves #36)

### CODE REVIEW

**Comment by ayoubmansar** [comment]
First... can you rebase off master? That will take care of some of the below points as well as the merge conflict. Also:
- I see that in your commit your `.gitignore` file is empty, however in #21 we added a comprehensive file. 
- Why are constants being added to the repo's `README`? Let's store them somewhere else... the repo `README` should be used to discuss the project at a high level (#20).
- Moreover to the prior point, why is `INPUT_FILE_PATH` a path to a file on your local directory (`/Users/ashwingodura/`). This should be a file that lives in the repo, no? Otherwise in deployment it won't find this file.
- Can you explain `ERROR_MESSAGE` (`"Acceptable ! appropriate representation requested resource could found server . error generated Mod_Security ."`) Was it an intentional thing for this message to not make grammatical sense? I'm sorta confused.
- In #37 we fixed all the linting errors so the CI should be passing by default. Can you rebase and ensure that your changes are compliant with the linter?
- Can you add tests for `WebpageSearcher.py`, probably under the `SearchEngine` directory?

**Comment by ashwin-godura** [comment]
In the new commit:

1. Fixed the merge conflicts, ReadMe and .gitignore should be untouched
2. Fixed the linting errors
3. Added Tests for the search engine
4. Added some extra documentation

As for the error message, I was getting this message when trying to web scrape some websites. I've handled this situation by returning false in the add_link method. However, the link will still get added to the class but will only use keywords to search for it

**Comment by ayoubmansar** [comment]
Great job adding the tests. This looks almost good. 

One thing: could you also modify `.github/workflows/main.yml` and add your newly-created tests to this file? This file contains all the commands that Github Actions will use as part of our continuous integration. Being able to ensure that all of the search model tests pass on every commit will help catch regressions for the future.

I'm not sure if this is necessary, but you may need to modify the test file to return an exit code of `0` if all tests pass, and otherwise if any of the tests fail. This might not be required, e.g. if it does this automatically when one of your `assert` statements fails. If not, this addition will be necessary to signal to the CI that this job failed.

**Comment by ashwin-godura** [comment]
I added in the tests now and they are all passing

**Comment by ayoubmansar** [comment]
Thanks for making the above changes. LGTM

**Review by ayoubmansar — APPROVED** [review]

**Pull request merged**
